// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/worldstate/worldstate.proto

package worldstate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	FromId        string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_worldstate_worldstate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worldstate_worldstate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_worldstate_worldstate_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *TransferRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *TransferRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *TransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_proto_worldstate_worldstate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worldstate_worldstate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_worldstate_worldstate_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_worldstate_worldstate_proto protoreflect.FileDescriptor

const file_proto_worldstate_worldstate_proto_rawDesc = "" +
	"\n" +
	"!proto/worldstate/worldstate.proto\x12\n" +
	"worldstate\"m\n" +
	"\x0fTransferRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x03 \x01(\tR\x04toId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"<\n" +
	"\x10TransferResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2Z\n" +
	"\x11WorldStateService\x12E\n" +
	"\bTransfer\x12\x1b.worldstate.TransferRequest\x1a\x1c.worldstate.TransferResponseB\x1bZ\x19ledgerdb/proto/worldstateb\x06proto3"

var (
	file_proto_worldstate_worldstate_proto_rawDescOnce sync.Once
	file_proto_worldstate_worldstate_proto_rawDescData []byte
)

func file_proto_worldstate_worldstate_proto_rawDescGZIP() []byte {
	file_proto_worldstate_worldstate_proto_rawDescOnce.Do(func() {
		file_proto_worldstate_worldstate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worldstate_worldstate_proto_rawDesc), len(file_proto_worldstate_worldstate_proto_rawDesc)))
	})
	return file_proto_worldstate_worldstate_proto_rawDescData
}

var file_proto_worldstate_worldstate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_worldstate_worldstate_proto_goTypes = []any{
	(*TransferRequest)(nil),  // 0: worldstate.TransferRequest
	(*TransferResponse)(nil), // 1: worldstate.TransferResponse
}
var file_proto_worldstate_worldstate_proto_depIdxs = []int32{
	0, // 0: worldstate.WorldStateService.Transfer:input_type -> worldstate.TransferRequest
	1, // 1: worldstate.WorldStateService.Transfer:output_type -> worldstate.TransferResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_worldstate_worldstate_proto_init() }
func file_proto_worldstate_worldstate_proto_init() {
	if File_proto_worldstate_worldstate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worldstate_worldstate_proto_rawDesc), len(file_proto_worldstate_worldstate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worldstate_worldstate_proto_goTypes,
		DependencyIndexes: file_proto_worldstate_worldstate_proto_depIdxs,
		MessageInfos:      file_proto_worldstate_worldstate_proto_msgTypes,
	}.Build()
	File_proto_worldstate_worldstate_proto = out.File
	file_proto_worldstate_worldstate_proto_goTypes = nil
	file_proto_worldstate_worldstate_proto_depIdxs = nil
}
