syntax = "proto3";

package worldstate;

option go_package = "StorageKernel/proto/worldstate";

service WorldStateService {
  rpc Transfer(TransferRequest) returns (TransferResponse);
  rpc OfflineWithdraw(OfflineWithdrawRequest) returns (OfflineWithdrawResponse);
  rpc OfflineDeposit(OfflineDepositRequest) returns (OfflineDepositResponse);
  rpc CreateAccount(CreateAccountRequest) returns (CreateAccountResponse);
  rpc ChangeAccountStatus(ChangeAccountStatusRequest) returns (ChangeAccountStatusResponse);
  rpc GetAccountsTier(GetAccountsTierRequest) returns (GetAccountsTierResponse);
}

message TransferRequest {
  string nonce   = 1;
  string from_id = 2;
  string to_id   = 3;
  int64  amount  = 4;
  bool offline_transaction = 5;
}

message TransferResponse {
  bool   ok      = 1;
  string message = 2;
}

message OfflineWithdrawRequest {
  string nonce   = 1;
  string account_id = 2;
  int64  amount  = 3;
}
message OfflineWithdrawResponse {
  bool   ok      = 1;
  string message = 2;
}
message OfflineDepositRequest {
  string nonce   = 1;
  string account_id = 2;
  int64  amount  = 3;
}
message OfflineDepositResponse {
  bool   ok      = 1;
  string message = 2;
}

message CreateAccountRequest {
  string nonce   = 1;
  string account_id = 2;
  int64  balance  = 3;
  string tier = 4;
}
message CreateAccountResponse {
  bool   ok      = 1;
  string message = 2;
}

message ChangeAccountStatusRequest {
  string account_id = 1;
  string status = 2;
  string reason = 3;
}
message ChangeAccountStatusResponse {
  bool   ok      = 1;
  string message = 2;
}

message GetAccountsTierRequest {
  string sender_account_id = 1;
  string receiver_account_id = 2;
}
message GetAccountsTierResponse {
  bool   ok      = 1;
  string message = 2;
  string sender_tier = 3;
  string receiver_tier = 4;
}