// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: worldstate.proto

package worldstate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Nonce              string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	FromId             string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId               string                 `protobuf:"bytes,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Amount             int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	OfflineTransaction bool                   `protobuf:"varint,5,opt,name=offline_transaction,json=offlineTransaction,proto3" json:"offline_transaction,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_worldstate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *TransferRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *TransferRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *TransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetOfflineTransaction() bool {
	if x != nil {
		return x.OfflineTransaction
	}
	return false
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_worldstate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OfflineWithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineWithdrawRequest) Reset() {
	*x = OfflineWithdrawRequest{}
	mi := &file_worldstate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineWithdrawRequest) ProtoMessage() {}

func (x *OfflineWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineWithdrawRequest.ProtoReflect.Descriptor instead.
func (*OfflineWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{2}
}

func (x *OfflineWithdrawRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *OfflineWithdrawRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *OfflineWithdrawRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OfflineWithdrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineWithdrawResponse) Reset() {
	*x = OfflineWithdrawResponse{}
	mi := &file_worldstate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineWithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineWithdrawResponse) ProtoMessage() {}

func (x *OfflineWithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineWithdrawResponse.ProtoReflect.Descriptor instead.
func (*OfflineWithdrawResponse) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{3}
}

func (x *OfflineWithdrawResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OfflineWithdrawResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OfflineDepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineDepositRequest) Reset() {
	*x = OfflineDepositRequest{}
	mi := &file_worldstate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineDepositRequest) ProtoMessage() {}

func (x *OfflineDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineDepositRequest.ProtoReflect.Descriptor instead.
func (*OfflineDepositRequest) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{4}
}

func (x *OfflineDepositRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *OfflineDepositRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *OfflineDepositRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OfflineDepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineDepositResponse) Reset() {
	*x = OfflineDepositResponse{}
	mi := &file_worldstate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineDepositResponse) ProtoMessage() {}

func (x *OfflineDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineDepositResponse.ProtoReflect.Descriptor instead.
func (*OfflineDepositResponse) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{5}
}

func (x *OfflineDepositResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OfflineDepositResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Tier          string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_worldstate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAccountRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *CreateAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateAccountRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateAccountRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_worldstate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAccountResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_worldstate_proto protoreflect.FileDescriptor

const file_worldstate_proto_rawDesc = "" +
	"\n" +
	"\x10worldstate.proto\x12\n" +
	"worldstate\"\x9e\x01\n" +
	"\x0fTransferRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x03 \x01(\tR\x04toId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12/\n" +
	"\x13offline_transaction\x18\x05 \x01(\bR\x12offlineTransaction\"<\n" +
	"\x10TransferResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"e\n" +
	"\x16OfflineWithdrawRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"C\n" +
	"\x17OfflineWithdrawResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"d\n" +
	"\x15OfflineDepositRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"B\n" +
	"\x16OfflineDepositResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"y\n" +
	"\x14CreateAccountRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\"A\n" +
	"\x15CreateAccountResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe5\x02\n" +
	"\x11WorldStateService\x12E\n" +
	"\bTransfer\x12\x1b.worldstate.TransferRequest\x1a\x1c.worldstate.TransferResponse\x12Z\n" +
	"\x0fOfflineWithdraw\x12\".worldstate.OfflineWithdrawRequest\x1a#.worldstate.OfflineWithdrawResponse\x12W\n" +
	"\x0eOfflineDeposit\x12!.worldstate.OfflineDepositRequest\x1a\".worldstate.OfflineDepositResponse\x12T\n" +
	"\rCreateAccount\x12 .worldstate.CreateAccountRequest\x1a!.worldstate.CreateAccountResponseB Z\x1eStorageKernel/proto/worldstateb\x06proto3"

var (
	file_worldstate_proto_rawDescOnce sync.Once
	file_worldstate_proto_rawDescData []byte
)

func file_worldstate_proto_rawDescGZIP() []byte {
	file_worldstate_proto_rawDescOnce.Do(func() {
		file_worldstate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worldstate_proto_rawDesc), len(file_worldstate_proto_rawDesc)))
	})
	return file_worldstate_proto_rawDescData
}

var file_worldstate_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_worldstate_proto_goTypes = []any{
	(*TransferRequest)(nil),         // 0: worldstate.TransferRequest
	(*TransferResponse)(nil),        // 1: worldstate.TransferResponse
	(*OfflineWithdrawRequest)(nil),  // 2: worldstate.OfflineWithdrawRequest
	(*OfflineWithdrawResponse)(nil), // 3: worldstate.OfflineWithdrawResponse
	(*OfflineDepositRequest)(nil),   // 4: worldstate.OfflineDepositRequest
	(*OfflineDepositResponse)(nil),  // 5: worldstate.OfflineDepositResponse
	(*CreateAccountRequest)(nil),    // 6: worldstate.CreateAccountRequest
	(*CreateAccountResponse)(nil),   // 7: worldstate.CreateAccountResponse
}
var file_worldstate_proto_depIdxs = []int32{
	0, // 0: worldstate.WorldStateService.Transfer:input_type -> worldstate.TransferRequest
	2, // 1: worldstate.WorldStateService.OfflineWithdraw:input_type -> worldstate.OfflineWithdrawRequest
	4, // 2: worldstate.WorldStateService.OfflineDeposit:input_type -> worldstate.OfflineDepositRequest
	6, // 3: worldstate.WorldStateService.CreateAccount:input_type -> worldstate.CreateAccountRequest
	1, // 4: worldstate.WorldStateService.Transfer:output_type -> worldstate.TransferResponse
	3, // 5: worldstate.WorldStateService.OfflineWithdraw:output_type -> worldstate.OfflineWithdrawResponse
	5, // 6: worldstate.WorldStateService.OfflineDeposit:output_type -> worldstate.OfflineDepositResponse
	7, // 7: worldstate.WorldStateService.CreateAccount:output_type -> worldstate.CreateAccountResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_worldstate_proto_init() }
func file_worldstate_proto_init() {
	if File_worldstate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worldstate_proto_rawDesc), len(file_worldstate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worldstate_proto_goTypes,
		DependencyIndexes: file_worldstate_proto_depIdxs,
		MessageInfos:      file_worldstate_proto_msgTypes,
	}.Build()
	File_worldstate_proto = out.File
	file_worldstate_proto_goTypes = nil
	file_worldstate_proto_depIdxs = nil
}
