// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: worldstate.proto

package worldstate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Nonce              string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	FromId             string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId               string                 `protobuf:"bytes,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Amount             int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	OfflineTransaction bool                   `protobuf:"varint,5,opt,name=offline_transaction,json=offlineTransaction,proto3" json:"offline_transaction,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_worldstate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *TransferRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *TransferRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *TransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetOfflineTransaction() bool {
	if x != nil {
		return x.OfflineTransaction
	}
	return false
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_worldstate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OfflineWithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineWithdrawRequest) Reset() {
	*x = OfflineWithdrawRequest{}
	mi := &file_worldstate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineWithdrawRequest) ProtoMessage() {}

func (x *OfflineWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineWithdrawRequest.ProtoReflect.Descriptor instead.
func (*OfflineWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{2}
}

func (x *OfflineWithdrawRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *OfflineWithdrawRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *OfflineWithdrawRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OfflineWithdrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineWithdrawResponse) Reset() {
	*x = OfflineWithdrawResponse{}
	mi := &file_worldstate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineWithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineWithdrawResponse) ProtoMessage() {}

func (x *OfflineWithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineWithdrawResponse.ProtoReflect.Descriptor instead.
func (*OfflineWithdrawResponse) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{3}
}

func (x *OfflineWithdrawResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OfflineWithdrawResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OfflineDepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineDepositRequest) Reset() {
	*x = OfflineDepositRequest{}
	mi := &file_worldstate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineDepositRequest) ProtoMessage() {}

func (x *OfflineDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineDepositRequest.ProtoReflect.Descriptor instead.
func (*OfflineDepositRequest) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{4}
}

func (x *OfflineDepositRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *OfflineDepositRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *OfflineDepositRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OfflineDepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineDepositResponse) Reset() {
	*x = OfflineDepositResponse{}
	mi := &file_worldstate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineDepositResponse) ProtoMessage() {}

func (x *OfflineDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineDepositResponse.ProtoReflect.Descriptor instead.
func (*OfflineDepositResponse) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{5}
}

func (x *OfflineDepositResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OfflineDepositResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Tier          string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_worldstate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAccountRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *CreateAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateAccountRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateAccountRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_worldstate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAccountResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChangeAccountStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeAccountStatusRequest) Reset() {
	*x = ChangeAccountStatusRequest{}
	mi := &file_worldstate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeAccountStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAccountStatusRequest) ProtoMessage() {}

func (x *ChangeAccountStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAccountStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeAccountStatusRequest) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeAccountStatusRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ChangeAccountStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ChangeAccountStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeAccountStatusResponse) Reset() {
	*x = ChangeAccountStatusResponse{}
	mi := &file_worldstate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeAccountStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAccountStatusResponse) ProtoMessage() {}

func (x *ChangeAccountStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAccountStatusResponse.ProtoReflect.Descriptor instead.
func (*ChangeAccountStatusResponse) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeAccountStatusResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ChangeAccountStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAccountsTierRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SenderAccountId   string                 `protobuf:"bytes,1,opt,name=sender_account_id,json=senderAccountId,proto3" json:"sender_account_id,omitempty"`
	ReceiverAccountId string                 `protobuf:"bytes,2,opt,name=receiver_account_id,json=receiverAccountId,proto3" json:"receiver_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAccountsTierRequest) Reset() {
	*x = GetAccountsTierRequest{}
	mi := &file_worldstate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsTierRequest) ProtoMessage() {}

func (x *GetAccountsTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsTierRequest.ProtoReflect.Descriptor instead.
func (*GetAccountsTierRequest) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{10}
}

func (x *GetAccountsTierRequest) GetSenderAccountId() string {
	if x != nil {
		return x.SenderAccountId
	}
	return ""
}

func (x *GetAccountsTierRequest) GetReceiverAccountId() string {
	if x != nil {
		return x.ReceiverAccountId
	}
	return ""
}

type GetAccountsTierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SenderTier    string                 `protobuf:"bytes,3,opt,name=sender_tier,json=senderTier,proto3" json:"sender_tier,omitempty"`
	ReceiverTier  string                 `protobuf:"bytes,4,opt,name=receiver_tier,json=receiverTier,proto3" json:"receiver_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsTierResponse) Reset() {
	*x = GetAccountsTierResponse{}
	mi := &file_worldstate_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsTierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsTierResponse) ProtoMessage() {}

func (x *GetAccountsTierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldstate_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsTierResponse.ProtoReflect.Descriptor instead.
func (*GetAccountsTierResponse) Descriptor() ([]byte, []int) {
	return file_worldstate_proto_rawDescGZIP(), []int{11}
}

func (x *GetAccountsTierResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetAccountsTierResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAccountsTierResponse) GetSenderTier() string {
	if x != nil {
		return x.SenderTier
	}
	return ""
}

func (x *GetAccountsTierResponse) GetReceiverTier() string {
	if x != nil {
		return x.ReceiverTier
	}
	return ""
}

var File_worldstate_proto protoreflect.FileDescriptor

const file_worldstate_proto_rawDesc = "" +
	"\n" +
	"\x10worldstate.proto\x12\n" +
	"worldstate\"\x9e\x01\n" +
	"\x0fTransferRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x03 \x01(\tR\x04toId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12/\n" +
	"\x13offline_transaction\x18\x05 \x01(\bR\x12offlineTransaction\"<\n" +
	"\x10TransferResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"e\n" +
	"\x16OfflineWithdrawRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"C\n" +
	"\x17OfflineWithdrawResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"d\n" +
	"\x15OfflineDepositRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"B\n" +
	"\x16OfflineDepositResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"y\n" +
	"\x14CreateAccountRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\"A\n" +
	"\x15CreateAccountResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"\x1aChangeAccountStatusRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"G\n" +
	"\x1bChangeAccountStatusResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"t\n" +
	"\x16GetAccountsTierRequest\x12*\n" +
	"\x11sender_account_id\x18\x01 \x01(\tR\x0fsenderAccountId\x12.\n" +
	"\x13receiver_account_id\x18\x02 \x01(\tR\x11receiverAccountId\"\x89\x01\n" +
	"\x17GetAccountsTierResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vsender_tier\x18\x03 \x01(\tR\n" +
	"senderTier\x12#\n" +
	"\rreceiver_tier\x18\x04 \x01(\tR\freceiverTier2\xa9\x04\n" +
	"\x11WorldStateService\x12E\n" +
	"\bTransfer\x12\x1b.worldstate.TransferRequest\x1a\x1c.worldstate.TransferResponse\x12Z\n" +
	"\x0fOfflineWithdraw\x12\".worldstate.OfflineWithdrawRequest\x1a#.worldstate.OfflineWithdrawResponse\x12W\n" +
	"\x0eOfflineDeposit\x12!.worldstate.OfflineDepositRequest\x1a\".worldstate.OfflineDepositResponse\x12T\n" +
	"\rCreateAccount\x12 .worldstate.CreateAccountRequest\x1a!.worldstate.CreateAccountResponse\x12f\n" +
	"\x13ChangeAccountStatus\x12&.worldstate.ChangeAccountStatusRequest\x1a'.worldstate.ChangeAccountStatusResponse\x12Z\n" +
	"\x0fGetAccountsTier\x12\".worldstate.GetAccountsTierRequest\x1a#.worldstate.GetAccountsTierResponseB Z\x1eStorageKernel/proto/worldstateb\x06proto3"

var (
	file_worldstate_proto_rawDescOnce sync.Once
	file_worldstate_proto_rawDescData []byte
)

func file_worldstate_proto_rawDescGZIP() []byte {
	file_worldstate_proto_rawDescOnce.Do(func() {
		file_worldstate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worldstate_proto_rawDesc), len(file_worldstate_proto_rawDesc)))
	})
	return file_worldstate_proto_rawDescData
}

var file_worldstate_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_worldstate_proto_goTypes = []any{
	(*TransferRequest)(nil),             // 0: worldstate.TransferRequest
	(*TransferResponse)(nil),            // 1: worldstate.TransferResponse
	(*OfflineWithdrawRequest)(nil),      // 2: worldstate.OfflineWithdrawRequest
	(*OfflineWithdrawResponse)(nil),     // 3: worldstate.OfflineWithdrawResponse
	(*OfflineDepositRequest)(nil),       // 4: worldstate.OfflineDepositRequest
	(*OfflineDepositResponse)(nil),      // 5: worldstate.OfflineDepositResponse
	(*CreateAccountRequest)(nil),        // 6: worldstate.CreateAccountRequest
	(*CreateAccountResponse)(nil),       // 7: worldstate.CreateAccountResponse
	(*ChangeAccountStatusRequest)(nil),  // 8: worldstate.ChangeAccountStatusRequest
	(*ChangeAccountStatusResponse)(nil), // 9: worldstate.ChangeAccountStatusResponse
	(*GetAccountsTierRequest)(nil),      // 10: worldstate.GetAccountsTierRequest
	(*GetAccountsTierResponse)(nil),     // 11: worldstate.GetAccountsTierResponse
}
var file_worldstate_proto_depIdxs = []int32{
	0,  // 0: worldstate.WorldStateService.Transfer:input_type -> worldstate.TransferRequest
	2,  // 1: worldstate.WorldStateService.OfflineWithdraw:input_type -> worldstate.OfflineWithdrawRequest
	4,  // 2: worldstate.WorldStateService.OfflineDeposit:input_type -> worldstate.OfflineDepositRequest
	6,  // 3: worldstate.WorldStateService.CreateAccount:input_type -> worldstate.CreateAccountRequest
	8,  // 4: worldstate.WorldStateService.ChangeAccountStatus:input_type -> worldstate.ChangeAccountStatusRequest
	10, // 5: worldstate.WorldStateService.GetAccountsTier:input_type -> worldstate.GetAccountsTierRequest
	1,  // 6: worldstate.WorldStateService.Transfer:output_type -> worldstate.TransferResponse
	3,  // 7: worldstate.WorldStateService.OfflineWithdraw:output_type -> worldstate.OfflineWithdrawResponse
	5,  // 8: worldstate.WorldStateService.OfflineDeposit:output_type -> worldstate.OfflineDepositResponse
	7,  // 9: worldstate.WorldStateService.CreateAccount:output_type -> worldstate.CreateAccountResponse
	9,  // 10: worldstate.WorldStateService.ChangeAccountStatus:output_type -> worldstate.ChangeAccountStatusResponse
	11, // 11: worldstate.WorldStateService.GetAccountsTier:output_type -> worldstate.GetAccountsTierResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_worldstate_proto_init() }
func file_worldstate_proto_init() {
	if File_worldstate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worldstate_proto_rawDesc), len(file_worldstate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worldstate_proto_goTypes,
		DependencyIndexes: file_worldstate_proto_depIdxs,
		MessageInfos:      file_worldstate_proto_msgTypes,
	}.Build()
	File_worldstate_proto = out.File
	file_worldstate_proto_goTypes = nil
	file_worldstate_proto_depIdxs = nil
}
