// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: worldstate.proto

package worldstate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorldStateService_Transfer_FullMethodName        = "/worldstate.WorldStateService/Transfer"
	WorldStateService_OfflineWithdraw_FullMethodName = "/worldstate.WorldStateService/OfflineWithdraw"
	WorldStateService_OfflineDeposit_FullMethodName  = "/worldstate.WorldStateService/OfflineDeposit"
	WorldStateService_CreateAccount_FullMethodName   = "/worldstate.WorldStateService/CreateAccount"
)

// WorldStateServiceClient is the client API for WorldStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorldStateServiceClient interface {
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	OfflineWithdraw(ctx context.Context, in *OfflineWithdrawRequest, opts ...grpc.CallOption) (*OfflineWithdrawResponse, error)
	OfflineDeposit(ctx context.Context, in *OfflineDepositRequest, opts ...grpc.CallOption) (*OfflineDepositResponse, error)
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
}

type worldStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldStateServiceClient(cc grpc.ClientConnInterface) WorldStateServiceClient {
	return &worldStateServiceClient{cc}
}

func (c *worldStateServiceClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, WorldStateService_Transfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldStateServiceClient) OfflineWithdraw(ctx context.Context, in *OfflineWithdrawRequest, opts ...grpc.CallOption) (*OfflineWithdrawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfflineWithdrawResponse)
	err := c.cc.Invoke(ctx, WorldStateService_OfflineWithdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldStateServiceClient) OfflineDeposit(ctx context.Context, in *OfflineDepositRequest, opts ...grpc.CallOption) (*OfflineDepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfflineDepositResponse)
	err := c.cc.Invoke(ctx, WorldStateService_OfflineDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldStateServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, WorldStateService_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorldStateServiceServer is the server API for WorldStateService service.
// All implementations must embed UnimplementedWorldStateServiceServer
// for forward compatibility.
type WorldStateServiceServer interface {
	Transfer(context.Context, *TransferRequest) (*TransferResponse, error)
	OfflineWithdraw(context.Context, *OfflineWithdrawRequest) (*OfflineWithdrawResponse, error)
	OfflineDeposit(context.Context, *OfflineDepositRequest) (*OfflineDepositResponse, error)
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	mustEmbedUnimplementedWorldStateServiceServer()
}

// UnimplementedWorldStateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorldStateServiceServer struct{}

func (UnimplementedWorldStateServiceServer) Transfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedWorldStateServiceServer) OfflineWithdraw(context.Context, *OfflineWithdrawRequest) (*OfflineWithdrawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OfflineWithdraw not implemented")
}
func (UnimplementedWorldStateServiceServer) OfflineDeposit(context.Context, *OfflineDepositRequest) (*OfflineDepositResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OfflineDeposit not implemented")
}
func (UnimplementedWorldStateServiceServer) CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedWorldStateServiceServer) mustEmbedUnimplementedWorldStateServiceServer() {}
func (UnimplementedWorldStateServiceServer) testEmbeddedByValue()                           {}

// UnsafeWorldStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorldStateServiceServer will
// result in compilation errors.
type UnsafeWorldStateServiceServer interface {
	mustEmbedUnimplementedWorldStateServiceServer()
}

func RegisterWorldStateServiceServer(s grpc.ServiceRegistrar, srv WorldStateServiceServer) {
	// If the following call panics, it indicates UnimplementedWorldStateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorldStateService_ServiceDesc, srv)
}

func _WorldStateService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldStateServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldStateService_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldStateServiceServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldStateService_OfflineWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfflineWithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldStateServiceServer).OfflineWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldStateService_OfflineWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldStateServiceServer).OfflineWithdraw(ctx, req.(*OfflineWithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldStateService_OfflineDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfflineDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldStateServiceServer).OfflineDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldStateService_OfflineDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldStateServiceServer).OfflineDeposit(ctx, req.(*OfflineDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldStateService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldStateServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldStateService_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldStateServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorldStateService_ServiceDesc is the grpc.ServiceDesc for WorldStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorldStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worldstate.WorldStateService",
	HandlerType: (*WorldStateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transfer",
			Handler:    _WorldStateService_Transfer_Handler,
		},
		{
			MethodName: "OfflineWithdraw",
			Handler:    _WorldStateService_OfflineWithdraw_Handler,
		},
		{
			MethodName: "OfflineDeposit",
			Handler:    _WorldStateService_OfflineDeposit_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _WorldStateService_CreateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worldstate.proto",
}
