// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: TransactionsStore.proto

package TransactionsStore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Simple ack
type StoreAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BatchId       string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreAck) Reset() {
	*x = StoreAck{}
	mi := &file_TransactionsStore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreAck) ProtoMessage() {}

func (x *StoreAck) ProtoReflect() protoreflect.Message {
	mi := &file_TransactionsStore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreAck.ProtoReflect.Descriptor instead.
func (*StoreAck) Descriptor() ([]byte, []int) {
	return file_TransactionsStore_proto_rawDescGZIP(), []int{0}
}

func (x *StoreAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

var File_TransactionsStore_proto protoreflect.FileDescriptor

const file_TransactionsStore_proto_rawDesc = "" +
	"\n" +
	"\x17TransactionsStore.proto\x12\x11TransactionsStore\x1a\x19google/protobuf/any.proto\"?\n" +
	"\bStoreAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId2V\n" +
	"\x18TransactionsStoreService\x12:\n" +
	"\x05Store\x12\x14.google.protobuf.Any\x1a\x1b.TransactionsStore.StoreAckB'Z%StorageKernel/proto/TransactionsStoreb\x06proto3"

var (
	file_TransactionsStore_proto_rawDescOnce sync.Once
	file_TransactionsStore_proto_rawDescData []byte
)

func file_TransactionsStore_proto_rawDescGZIP() []byte {
	file_TransactionsStore_proto_rawDescOnce.Do(func() {
		file_TransactionsStore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TransactionsStore_proto_rawDesc), len(file_TransactionsStore_proto_rawDesc)))
	})
	return file_TransactionsStore_proto_rawDescData
}

var file_TransactionsStore_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TransactionsStore_proto_goTypes = []any{
	(*StoreAck)(nil),  // 0: TransactionsStore.StoreAck
	(*anypb.Any)(nil), // 1: google.protobuf.Any
}
var file_TransactionsStore_proto_depIdxs = []int32{
	1, // 0: TransactionsStore.TransactionsStoreService.Store:input_type -> google.protobuf.Any
	0, // 1: TransactionsStore.TransactionsStoreService.Store:output_type -> TransactionsStore.StoreAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TransactionsStore_proto_init() }
func file_TransactionsStore_proto_init() {
	if File_TransactionsStore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TransactionsStore_proto_rawDesc), len(file_TransactionsStore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TransactionsStore_proto_goTypes,
		DependencyIndexes: file_TransactionsStore_proto_depIdxs,
		MessageInfos:      file_TransactionsStore_proto_msgTypes,
	}.Build()
	File_TransactionsStore_proto = out.File
	file_TransactionsStore_proto_goTypes = nil
	file_TransactionsStore_proto_depIdxs = nil
}
