// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: TransactionsStore.proto

package TransactionsStore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionsStoreService_Store_FullMethodName = "/TransactionsStore.TransactionsStoreService/Store"
)

// TransactionsStoreServiceClient is the client API for TransactionsStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionsStoreServiceClient interface {
	Store(ctx context.Context, in *anypb.Any, opts ...grpc.CallOption) (*StoreAck, error)
}

type transactionsStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionsStoreServiceClient(cc grpc.ClientConnInterface) TransactionsStoreServiceClient {
	return &transactionsStoreServiceClient{cc}
}

func (c *transactionsStoreServiceClient) Store(ctx context.Context, in *anypb.Any, opts ...grpc.CallOption) (*StoreAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreAck)
	err := c.cc.Invoke(ctx, TransactionsStoreService_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionsStoreServiceServer is the server API for TransactionsStoreService service.
// All implementations must embed UnimplementedTransactionsStoreServiceServer
// for forward compatibility.
type TransactionsStoreServiceServer interface {
	Store(context.Context, *anypb.Any) (*StoreAck, error)
	mustEmbedUnimplementedTransactionsStoreServiceServer()
}

// UnimplementedTransactionsStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionsStoreServiceServer struct{}

func (UnimplementedTransactionsStoreServiceServer) Store(context.Context, *anypb.Any) (*StoreAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedTransactionsStoreServiceServer) mustEmbedUnimplementedTransactionsStoreServiceServer() {
}
func (UnimplementedTransactionsStoreServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionsStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionsStoreServiceServer will
// result in compilation errors.
type UnsafeTransactionsStoreServiceServer interface {
	mustEmbedUnimplementedTransactionsStoreServiceServer()
}

func RegisterTransactionsStoreServiceServer(s grpc.ServiceRegistrar, srv TransactionsStoreServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionsStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionsStoreService_ServiceDesc, srv)
}

func _TransactionsStoreService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(anypb.Any)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsStoreServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionsStoreService_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsStoreServiceServer).Store(ctx, req.(*anypb.Any))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionsStoreService_ServiceDesc is the grpc.ServiceDesc for TransactionsStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionsStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TransactionsStore.TransactionsStoreService",
	HandlerType: (*TransactionsStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _TransactionsStoreService_Store_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "TransactionsStore.proto",
}
