// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: TransactionsStore.proto

package TransactionsStore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionRequest represents a request to store a transaction in the transactions store
type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	FromWallet    string                 `protobuf:"bytes,2,opt,name=from_wallet,json=fromWallet,proto3" json:"from_wallet,omitempty"`
	ToWallet      string                 `protobuf:"bytes,3,opt,name=to_wallet,json=toWallet,proto3" json:"to_wallet,omitempty"`
	Amount        float32                `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Nonce         string                 `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Hash          string                 `protobuf:"bytes,7,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_TransactionsStore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TransactionsStore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_TransactionsStore_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *TransactionRequest) GetFromWallet() string {
	if x != nil {
		return x.FromWallet
	}
	return ""
}

func (x *TransactionRequest) GetToWallet() string {
	if x != nil {
		return x.ToWallet
	}
	return ""
}

func (x *TransactionRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransactionRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *TransactionRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// The server responds with a receipt
// then it will start the indexing process
type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	FromWallet    string                 `protobuf:"bytes,3,opt,name=from_wallet,json=fromWallet,proto3" json:"from_wallet,omitempty"`
	ToWallet      string                 `protobuf:"bytes,4,opt,name=to_wallet,json=toWallet,proto3" json:"to_wallet,omitempty"`
	Amount        float32                `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_TransactionsStore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TransactionsStore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_TransactionsStore_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *TransactionResponse) GetFromWallet() string {
	if x != nil {
		return x.FromWallet
	}
	return ""
}

func (x *TransactionResponse) GetToWallet() string {
	if x != nil {
		return x.ToWallet
	}
	return ""
}

func (x *TransactionResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_TransactionsStore_proto protoreflect.FileDescriptor

const file_TransactionsStore_proto_rawDesc = "" +
	"\n" +
	"\x17TransactionsStore.proto\x12\x11TransactionsStore\"\xc6\x01\n" +
	"\x12TransactionRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x1f\n" +
	"\vfrom_wallet\x18\x02 \x01(\tR\n" +
	"fromWallet\x12\x1b\n" +
	"\tto_wallet\x18\x03 \x01(\tR\btoWallet\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x02R\x06amount\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\tR\x05nonce\x12\x12\n" +
	"\x04hash\x18\a \x01(\tR\x04hash\"\xc4\x01\n" +
	"\x13TransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x1f\n" +
	"\vfrom_wallet\x18\x03 \x01(\tR\n" +
	"fromWallet\x12\x1b\n" +
	"\tto_wallet\x18\x04 \x01(\tR\btoWallet\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x02R\x06amount\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage2r\n" +
	"\x18TransactionsStoreService\x12V\n" +
	"\x05Store\x12%.TransactionsStore.TransactionRequest\x1a&.TransactionsStore.TransactionResponseB\"Z ledgerdb/proto/TransactionsStoreb\x06proto3"

var (
	file_TransactionsStore_proto_rawDescOnce sync.Once
	file_TransactionsStore_proto_rawDescData []byte
)

func file_TransactionsStore_proto_rawDescGZIP() []byte {
	file_TransactionsStore_proto_rawDescOnce.Do(func() {
		file_TransactionsStore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TransactionsStore_proto_rawDesc), len(file_TransactionsStore_proto_rawDesc)))
	})
	return file_TransactionsStore_proto_rawDescData
}

var file_TransactionsStore_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_TransactionsStore_proto_goTypes = []any{
	(*TransactionRequest)(nil),  // 0: TransactionsStore.TransactionRequest
	(*TransactionResponse)(nil), // 1: TransactionsStore.TransactionResponse
}
var file_TransactionsStore_proto_depIdxs = []int32{
	0, // 0: TransactionsStore.TransactionsStoreService.Store:input_type -> TransactionsStore.TransactionRequest
	1, // 1: TransactionsStore.TransactionsStoreService.Store:output_type -> TransactionsStore.TransactionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TransactionsStore_proto_init() }
func file_TransactionsStore_proto_init() {
	if File_TransactionsStore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TransactionsStore_proto_rawDesc), len(file_TransactionsStore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TransactionsStore_proto_goTypes,
		DependencyIndexes: file_TransactionsStore_proto_depIdxs,
		MessageInfos:      file_TransactionsStore_proto_msgTypes,
	}.Build()
	File_TransactionsStore_proto = out.File
	file_TransactionsStore_proto_goTypes = nil
	file_TransactionsStore_proto_depIdxs = nil
}
