// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ledgerserver.proto

package ledgerserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankPrefix    string                 `protobuf:"bytes,1,opt,name=bank_prefix,json=bankPrefix,proto3" json:"bank_prefix,omitempty"` // e.g. "000", "001"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_ledgerserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledgerserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_ledgerserver_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetBankPrefix() string {
	if x != nil {
		return x.BankPrefix
	}
	return ""
}

type TransactionReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	FromWallet    string                 `protobuf:"bytes,3,opt,name=from_wallet,json=fromWallet,proto3" json:"from_wallet,omitempty"`
	ToWallet      string                 `protobuf:"bytes,4,opt,name=to_wallet,json=toWallet,proto3" json:"to_wallet,omitempty"`
	Amount        float32                `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Nonce         string                 `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TimeStamp     string                 `protobuf:"bytes,8,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionReceipt) Reset() {
	*x = TransactionReceipt{}
	mi := &file_ledgerserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionReceipt) ProtoMessage() {}

func (x *TransactionReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_ledgerserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionReceipt.ProtoReflect.Descriptor instead.
func (*TransactionReceipt) Descriptor() ([]byte, []int) {
	return file_ledgerserver_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionReceipt) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TransactionReceipt) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *TransactionReceipt) GetFromWallet() string {
	if x != nil {
		return x.FromWallet
	}
	return ""
}

func (x *TransactionReceipt) GetToWallet() string {
	if x != nil {
		return x.ToWallet
	}
	return ""
}

func (x *TransactionReceipt) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionReceipt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransactionReceipt) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *TransactionReceipt) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	TimeStamp     string                 `protobuf:"bytes,2,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	FromWallet    string                 `protobuf:"bytes,3,opt,name=from_wallet,json=fromWallet,proto3" json:"from_wallet,omitempty"`
	ToWallet      string                 `protobuf:"bytes,4,opt,name=to_wallet,json=toWallet,proto3" json:"to_wallet,omitempty"`
	Amount        float32                `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Nonce         string                 `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Hash          string                 `protobuf:"bytes,8,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_ledgerserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_ledgerserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_ledgerserver_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Transaction) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *Transaction) GetFromWallet() string {
	if x != nil {
		return x.FromWallet
	}
	return ""
}

func (x *Transaction) GetToWallet() string {
	if x != nil {
		return x.ToWallet
	}
	return ""
}

func (x *Transaction) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Transaction) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *Transaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type TransactionsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionsBatch) Reset() {
	*x = TransactionsBatch{}
	mi := &file_ledgerserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsBatch) ProtoMessage() {}

func (x *TransactionsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_ledgerserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsBatch.ProtoReflect.Descriptor instead.
func (*TransactionsBatch) Descriptor() ([]byte, []int) {
	return file_ledgerserver_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionsBatch) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type ServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_ledgerserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledgerserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_ledgerserver_proto_rawDescGZIP(), []int{4}
}

func (x *ServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_ledgerserver_proto protoreflect.FileDescriptor

const file_ledgerserver_proto_rawDesc = "" +
	"\n" +
	"\x12ledgerserver.proto\x12\fLedgerServer\"3\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vbank_prefix\x18\x01 \x01(\tR\n" +
	"bankPrefix\"\xe5\x01\n" +
	"\x12TransactionReceipt\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x1f\n" +
	"\vfrom_wallet\x18\x03 \x01(\tR\n" +
	"fromWallet\x12\x1b\n" +
	"\tto_wallet\x18\x04 \x01(\tR\btoWallet\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x02R\x06amount\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x14\n" +
	"\x05nonce\x18\a \x01(\tR\x05nonce\x12\x1d\n" +
	"\n" +
	"time_stamp\x18\b \x01(\tR\ttimeStamp\"\xde\x01\n" +
	"\vTransaction\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x1d\n" +
	"\n" +
	"time_stamp\x18\x02 \x01(\tR\ttimeStamp\x12\x1f\n" +
	"\vfrom_wallet\x18\x03 \x01(\tR\n" +
	"fromWallet\x12\x1b\n" +
	"\tto_wallet\x18\x04 \x01(\tR\btoWallet\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x02R\x06amount\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x14\n" +
	"\x05nonce\x18\a \x01(\tR\x05nonce\x12\x12\n" +
	"\x04hash\x18\b \x01(\tR\x04hash\"R\n" +
	"\x11TransactionsBatch\x12=\n" +
	"\ftransactions\x18\x01 \x03(\v2\x19.LedgerServer.TransactionR\ftransactions\"*\n" +
	"\x0eServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2e\n" +
	"\x13TransactionsService\x12N\n" +
	"\vBatchAppend\x12\x1f.LedgerServer.TransactionsBatch\x1a\x1c.LedgerServer.ServerResponse\"\x002c\n" +
	"\x0eReceiptService\x12Q\n" +
	"\tSubscribe\x12\x1e.LedgerServer.SubscribeRequest\x1a .LedgerServer.TransactionReceipt\"\x000\x01B\x1fZ\x1dLedgerServer/api/ledgerserverb\x06proto3"

var (
	file_ledgerserver_proto_rawDescOnce sync.Once
	file_ledgerserver_proto_rawDescData []byte
)

func file_ledgerserver_proto_rawDescGZIP() []byte {
	file_ledgerserver_proto_rawDescOnce.Do(func() {
		file_ledgerserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledgerserver_proto_rawDesc), len(file_ledgerserver_proto_rawDesc)))
	})
	return file_ledgerserver_proto_rawDescData
}

var file_ledgerserver_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ledgerserver_proto_goTypes = []any{
	(*SubscribeRequest)(nil),   // 0: LedgerServer.SubscribeRequest
	(*TransactionReceipt)(nil), // 1: LedgerServer.TransactionReceipt
	(*Transaction)(nil),        // 2: LedgerServer.Transaction
	(*TransactionsBatch)(nil),  // 3: LedgerServer.TransactionsBatch
	(*ServerResponse)(nil),     // 4: LedgerServer.ServerResponse
}
var file_ledgerserver_proto_depIdxs = []int32{
	2, // 0: LedgerServer.TransactionsBatch.transactions:type_name -> LedgerServer.Transaction
	3, // 1: LedgerServer.TransactionsService.BatchAppend:input_type -> LedgerServer.TransactionsBatch
	0, // 2: LedgerServer.ReceiptService.Subscribe:input_type -> LedgerServer.SubscribeRequest
	4, // 3: LedgerServer.TransactionsService.BatchAppend:output_type -> LedgerServer.ServerResponse
	1, // 4: LedgerServer.ReceiptService.Subscribe:output_type -> LedgerServer.TransactionReceipt
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ledgerserver_proto_init() }
func file_ledgerserver_proto_init() {
	if File_ledgerserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledgerserver_proto_rawDesc), len(file_ledgerserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ledgerserver_proto_goTypes,
		DependencyIndexes: file_ledgerserver_proto_depIdxs,
		MessageInfos:      file_ledgerserver_proto_msgTypes,
	}.Build()
	File_ledgerserver_proto = out.File
	file_ledgerserver_proto_goTypes = nil
	file_ledgerserver_proto_depIdxs = nil
}
