syntax = "proto3";

option go_package = "LedgerServer/api/ledgerserver";

package LedgerServer;

// TransactionsService handles appending transaction batches from LedgerProxy
service TransactionsService {
    rpc BatchAppend(TransactionsBatch) returns (ServerResponse) {}
}

message Transaction {
    bool   status      = 1;
    string time_stamp  = 2;
    string from_wallet = 3;
    string to_wallet   = 4;
    float  amount      = 5;
    string message     = 6;
    string nonce       = 7;
    string hash        = 8;
}

message TransactionsBatch {
    repeated Transaction transactions = 1;
}

message ServerResponse {
    bool success = 1;
}
