syntax = "proto3";

option go_package = "LedgerProxy/api/pb";

package LedgerProxy;

service SecurityService {

    rpc CreateAccount(SecureRequest) returns (SecureResponse) {}

    rpc Execute(SecureRequest) returns (SecureResponse) {}
    rpc Sync(SecureRequestList) returns (SecureResponseList) {}

    rpc OfflineWithdraw(SecureRequest) returns (SecureResponse) {}
    rpc OfflineDeposit(SecureRequest) returns (SecureResponse) {}
    
}

message SecureRequest {
    bytes encrypted_data = 1; 
}

message SecureResponse {
    bool success = 1;
    string message = 2; // Optional: details about the result
}

message SecureRequestList {
    repeated SecureRequest requests = 1; 
}

message SecureResponseList {
    repeated SecureResponse responses =  1;
}


service ReceiptService {    
    // The bank sends its prefix (e.g. "000") and receives receipts
    rpc Subscribe(SubscribeRequest) returns (stream TransactionReceipt) {}
}

message SubscribeRequest {
    string bank_prefix = 1; // e.g. "000", "001"
}

message TransactionReceipt {
    string hash        = 1;
    bool   status      = 2;
    string from_wallet = 3;
    string to_wallet   = 4;
    int64  amount      = 5;
    string message     = 6;
    string nonce       = 7;
    string time_stamp  = 8;
    bool is_merchant = 9;
}